#!/usr/bin/env ruby -KU
require 'rubygems'
require 'bundler/setup'
require 'em-websocket'
require 'lib/ftang'

EventMachine.run do
  @channel =  EventMachine::Channel.new

  EventMachine::WebSocket.start(:host => '0.0.0.0', :port => 8081) do |ws|

    # damn kids got their javascript idioms in my ruby!
    ws.onopen {

      sid = @channel.subscribe { |msg| 
        ws.send(msg)
      }

      ws.onmessage { |msg|
        if 'quit' == msg
          ws.close_connection
        else
          command = Ftang::PlayerCommand.new(sid, msg)
          @channel.push(command.to_json)
        end
      }

      ws.onclose   {
        @channel.unsubscribe(sid)
        puts "closed #{sid}"
      }

      ws.send("hi there #{sid}")
      @channel.push("hello to #{sid}")

    }

  end

  # You could also use Rainbows! instead of Thin.
  # Any EM based Rack handler should do.
  Ftang::Server.run!(:port => 8080)

end
