#!/usr/bin/env ruby -KU
require 'rubygems'
require 'bundler/setup'
require 'em-websocket'
require 'lib/ftang'

EventMachine.run do     # <-- Changed EM to EventMachine

  EventMachine::WebSocket.start(:host => '0.0.0.0', :port => 8081) do |ws| # <-- Added |ws|

      @clients = Ftang::PlaylistPool.new

      ws.onopen {
        @clients.add(ws)
      }

      ws.onmessage { |msg|
        if 'quit' == msg
          ws.close_connection
        else
          command = Ftang::PlayerCommand.new(ws.request['Cookie'], msg)
          @clients.broadcast(command)
        end
      }

      ws.onclose   {
        @clients.delete(ws)
        puts 'close'
        ws.send "WebSocket closed"
      }

  end

  # You could also use Rainbows! instead of Thin.
  # Any EM based Rack handler should do.
  Ftang::Server.run!(:port => 8080)

end
