#!/usr/bin/env ruby -KU
require 'rubygems'
require 'bundler/setup'
require 'em-websocket'
require 'thin'
require 'lib/ftang'

EventMachine.run do     # <-- Changed EM to EventMachine

  EventMachine::WebSocket.start(:host => '0.0.0.0', :port => 8081) do |ws| # <-- Added |ws|
      # Websocket code here
      #
      js = %Q(
          {'jsonp' : function () { console.log('shirtz'); }}
      )

      ws.onopen {
             ws.send js
      }

      ws.onmessage { |msg|
          puts "got message #{msg}"
      }

      ws.onclose   {
          puts 'close'
          ws.send "WebSocket closed"
      }

  end

  # You could also use Rainbows! instead of Thin.
  # Any EM based Rack handler should do.
  FTANG.run!(:port => 8080)

end
